version: "3.8"
services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    ports:
      - "8080:8080"
    environment:
      - TIME_ADDITION_MS=1000
      - TIME_SUBTRACTION_MS=1000
      - TIME_MULTIPLICATION_MS=2000
      - TIME_DIVISION_MS=3000

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      - COMPUTING_POWER=5